[package]
name = "quest_sky_native"
version = "0.3.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = { version = "=0.5.4", features = ["api-4-6", "experimental-threads"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.140"
